name: PackIt
description: "A universal plugin manager for exteraGram/AyuGram. With the ability to add multiple replicas, as well as create your own."
id: shareui_packit
version: "0.1.0 Prototype"
author: "@shareui"
min_version: "12.2.10"
icon: packit/mf/frieren.png